language: node_js
node_js:
  - "8"

# Tests that the build process is working, in addition to the tests that run
before_script:
  - npm run build

after_script:
  - cat ./packages/cyto-core/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
